### ISSUE TITLE
year === 2022 ? 16.15.0 LTS : Node 16.13.0 LTS 

### ISSUE THREAD

**Issue by AmelianceSkyMusic** [EvgeniiMal/HTML-builder#10]
> !!! Проверка проводится на Node 16.13.0 LTS и без выполнения команды npm install в клонированном репозитории, так как любые сторонние модули запрещены.

Я так понимаю в 2022 году актуальная Node 16.13.0 LTS?

**Comment by EvgeniiMal** [comment]
Уже исправлено. Благодарю!
