### ISSUE TITLE
Старая версия ES в .eslintrc.js

### ISSUE THREAD

**Issue by Milena-Belianova** [EvgeniiMal/HTML-builder#12]
Здравствуйте. Столкнулась с тем, чтобы заработал топ-левел await его надо оборачивать в async, на это ругается линтер, но это уже не обязательно судя по документации.
Если в конфиге указать, что используется ES 2022, то все будет работать (у нас указана версия es2021). Может стоит обновить .eslintrc.js?

![image](https://user-images.githubusercontent.com/93428081/169504698-e8b968ed-c5a1-4f38-b678-3469243ea971.png)

**Comment by EvgeniiMal** [comment]
Во время выполнения таска правки в репозиторий не вносятся, но по завершению я обновлю. Благодарю за внимательность.
