### ISSUE TITLE
Уточнение требований

### ISSUE THREAD

**Issue by Vitaljano** [EvgeniiMal/HTML-builder#23]
Здраствуйте. Хочу предложить уточнение к описанию 3 задачи. К пункту "Информация должна выводиться только для файлов. Наличие информации о директориях считается ошибкой."  Добавить строку "(информация о файлах находящихся в подпапках выводиться не должна)"

**Comment by EvgeniiMal** [comment]
Добрый день! Я изменил формулировку на "Информация должна выводиться только для файлов содержащихся в 03-files-in-folder/secret-folder. Наличие информации о директориях считается ошибкой.".  Формулировка с файлами во вложенных папках в данном случае не совсем корректна, так как их нет(по задумке). Чтобы раскрыть эту тему первый же совет теперь предлагает ознакомиться с небольшой статьёй раскрывающей особенности работы git и назначение файла .gitkeep
