### ISSUE TITLE
Environment key "es2022" is unknown

### ISSUE THREAD

**Issue by in-in** [EvgeniiMal/HTML-builder#43]
При запуске `npx eslint .` появляется ошибка `Environment key "es2022" is unknown`
![23123185633](https://user-images.githubusercontent.com/8797432/235971619-cca9ecaa-6eca-4c36-83a7-f50d11d06745.png)

Судя по ченджлогу es2022 добавили в версии v8.9.0 - February 11, 2022. В проекте сейчас 7.32.0
https://github.com/eslint/eslint/blob/main/CHANGELOG.md\
![23123185457](https://user-images.githubusercontent.com/8797432/235972783-4e056c82-3821-4ece-a4a3-8000f14e2aa5.png)

Если обновить версию eslint, то линтер заработает как надо
![23123185654](https://user-images.githubusercontent.com/8797432/235973462-fcf6b99d-7f79-4dff-9a60-953cf7fd7519.png)
![23123185537](https://user-images.githubusercontent.com/8797432/235973533-3f2f8539-9c5a-4775-8db2-894eb126a1ad.png)

Возможно ещё стоит обновить версию `ecmaVersion` в конфиге до 13
![23123185902](https://user-images.githubusercontent.com/8797432/235974000-5496e8a5-4723-463f-8d02-2fa09d1b55c6.png)

**Comment by EvgeniiMal** [comment]
Привет! Спасибо за замечание. Сделаешь PR?
