### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by olyalass** [EvgeniiMal/HTML-builder#49]
В описании первого задания (https://github.com/EvgeniiMal/HTML-builder/tree/main/01-read-file) в абзаце `У вас будет несколько вариантов для того, чтобы направить ваш поток чтения в поток стандартного вывода(то есть консоль. Больше о стандартных потоках можно узнать [тут] ` в ссылке на Вики пропущен `/`, что приводит к поломке ссылки и переходу на главную страницу википедии вместо статьи
Правильная ссылка https://ru.wikipedia.org/wiki/Стандартные_потоки

**Comment by EvgeniiMal** [comment]
Боагодарю, исправлено
